project_id = "pcqompvgdgufjqibiwdj"

[functions.search-leads]
verify_jwt = false

[functions.get-leads-results]
verify_jwt = false

[functions.enrich-lead]
verify_jwt = false

[functions.create-campaign]
verify_jwt = false

[functions.send-campaign]
verify_jwt = false

[functions.get-credits]
verify_jwt = false

[functions.add-credits]
verify_jwt = false

[functions.invite-member]
verify_jwt = false

[functions.accept-invite]
verify_jwt = false

[functions.get-accounts]
verify_jwt = false

[functions.sync-accounts]
verify_jwt = false

[functions.save-account]
verify_jwt = false

[functions.webhook-account-status]
verify_jwt = false

[functions.create-connect-link]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.process-campaign-queue]
verify_jwt = false

[functions.webhook-messages]
verify_jwt = false

[functions.process-scheduled-campaigns]
verify_jwt = false

[functions.send-linkedin-invite]
verify_jwt = false

[functions.linkedin-search]
verify_jwt = false

[functions.linkedin-search-parameters]
verify_jwt = false

[functions.linkedin-enrich-lead]
verify_jwt = false

[functions.linkedin-check-connection]
verify_jwt = false

[functions.linkedin-engage]
verify_jwt = false

[functions.get-all-linkedin-accounts]
verify_jwt = false
